### ISSUE TITLE
Why the f*ck is the file to put in streaming assets an installer?

### ISSUE THREAD

**Issue by EggCPU** [CatsheeDev/devilishcheats-files#1]
When I downloaded this, the file displayed was an installer, when scanned by 3 seperate antivirus' and virus total each one flagged it as a trojan. The source code is also hidden, even on github. You need to start explaining yourself.

**Comment by CatsheeDev** [comment]
:skull: 

https://github.com/CatsheeDev/DevilishCheatsInstaller

**Comment by CatsheeDev** [comment]
this is too funny LMAO :skull: do some research the link to the installer repo is LITERALLY in the mod description

**Comment by CatsheeDev** [comment]
(ALSO ITS FLAGGED AS A TROJAN SINCE IT DOWNLOADS FILES TO UR PC)
